buildscript {
    ext.kotlinVersion = '1.9.22'
    repositories {
        mavenCentral()
        maven { url "https://plugins.gradle.org/m2/" }
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
        google()
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
        classpath "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin:$kotlinVersion-1.0.17"
        classpath 'com.android.tools.build:gradle:8.5.0'
        classpath "io.realm:realm-gradle-plugin:10.19.0"
        classpath 'app.cash.licensee:licensee-gradle-plugin:1.12.0'
    }
}

allprojects {
    repositories {
        mavenCentral()
        google()
        maven { url 'https://jitpack.io' }
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
        mavenLocal()
    }
}
