apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-parcelize'
apply plugin: 'kotlin-kapt'
apply plugin: 'com.google.devtools.ksp'
apply plugin: 'realm-android'
apply plugin: 'com.google.firebase.crashlytics'
apply plugin: 'com.google.firebase.firebase-perf'
apply plugin: 'app.cash.licensee'

Properties keyStoreProps = new Properties()
def keystoreProperties = file("keystore.properties")

if (keystoreProperties.exists()) {
    keyStoreProps.load(new FileInputStream(keystoreProperties))
}

Properties configProps = new Properties()
def configFile = file("config.properties")

if (configFile.exists()) {
    configProps.load(new FileInputStream(configFile))
}

android {
    namespace 'com.flipsidegroup.active10'
    compileSdk 35

    defaultConfig {
        applicationId "com.flipsidegroup.active10"
        minSdkVersion 23
        targetSdkVersion 35
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        versionCode 1176
        versionName "6.3.3-login"
        manifestPlaceholders = [
                appAuthRedirectScheme: 'active10'
        ]

        // Common properties, same for all flavors
        buildConfigField 'String', 'CERTIFICATE_1', "\"${configProps.getProperty('CERTIFICATE_1')}\""
        buildConfigField 'String', 'CERTIFICATE_2', "\"${configProps.getProperty('CERTIFICATE_2')}\""
        buildConfigField 'String', 'CERTIFICATE_3', "\"${configProps.getProperty('CERTIFICATE_3')}\""
        buildConfigField 'String', 'CERTIFICATE_4', "\"${configProps.getProperty('CERTIFICATE_4')}\""
        buildConfigField 'String', 'CERTIFICATE_5', "\"${configProps.getProperty('CERTIFICATE_5')}\""
        resValue 'string', 'google_maps_key', "\"${configProps.getProperty('GOOGLE_MAPS_API_KEY')}\""
    }

    signingConfigs {
        debug {
            storeFile file("debug.keystore")
            storePassword "android"
            keyAlias "androiddebugkey"
            keyPassword "android"
        }

        release {
            storeFile file("${keyStoreProps.getProperty('release.key.store', 'key.store')}")
            storePassword "${keyStoreProps.getProperty('release.key.store.password', 'key.store.password')}"
            keyAlias "${keyStoreProps.getProperty('release.key.alias', 'key.alias')}"
            keyPassword "${keyStoreProps.getProperty('release.key.alias.password', 'key.alias.password')}"
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }

    flavorDimensions = ["default"]
    productFlavors {
        dev {
            buildConfigField "String", "APP_ENDPOINT", "\"${configProps.getProperty('DEV_APP_ENDPOINT')}\""
            buildConfigField "String", "APP_ENDPOINT_V3", "\"${configProps.getProperty('DEV_APP_ENDPOINT_V3')}\""
            buildConfigField "String", "PARAGON_ENDPOINT", "\"${configProps.getProperty('DEV_PARAGON_ENDPOINT')}\""
            buildConfigField "String", "NHS_LOGIN_URL", "\"${configProps.getProperty('DEV_NHS_LOGIN_URL')}\""
            buildConfigField "String", "NHS_SETTINGS_URL", "\"${configProps.getProperty('DEV_NHS_SETTINGS_URL')}\""
            buildConfigField "String", "OIDC_DISCOVERY_URL", "\"${configProps.getProperty('DEV_OIDC_DISCOVERY_URL'}\""
            buildConfigField "String", "PARAGON_HEADER", "\"${configProps.getProperty('DEV_PARAGON_HEADER')}\""
            buildConfigField "String", "PARAGON_TOKEN", "\"${configProps.getProperty('DEV_PARAGON_TOKEN')}\""
            resValue "string", "app_name", "Active 10-DEV"
        }
        uat {
            buildConfigField "String", "APP_ENDPOINT", "\"${configProps.getProperty('UAT_APP_ENDPOINT')}\""
            buildConfigField "String", "APP_ENDPOINT_V3", "\"${configProps.getProperty('UAT_APP_ENDPOINT_V3')}\""
            buildConfigField "String", "PARAGON_ENDPOINT", "\"${configProps.getProperty('UAT_PARAGON_ENDPOINT')}\""
            buildConfigField "String", "PARAGON_HEADER", "\"${configProps.getProperty('UAT_PARAGON_HEADER')}\""
            buildConfigField "String", "NHS_LOGIN_URL", "\"${configProps.getProperty('UAT_NHS_LOGIN_URL')}\""
            buildConfigField "String", "NHS_SETTINGS_URL", "\"${configProps.getProperty('UAT_NHS_SETTINGS_URL')}\""
            buildConfigField "String", "OIDC_DISCOVERY_URL", "\"${configProps.getProperty('UAT_OIDC_DISCOVERY_URL')}\""
            buildConfigField "String", "PARAGON_TOKEN", "\"${configProps.getProperty('UAT_PARAGON_TOKEN')}\""
            resValue "string", "app_name", "Active 10-UAT"
            applicationId "com.flipsidegroup.active10.uat"
        }
        prod {
            buildConfigField "String", "APP_ENDPOINT", "\"${configProps.getProperty('PROD_APP_ENDPOINT')}\""
            buildConfigField "String", "APP_ENDPOINT_V3", "\"${configProps.getProperty('PROD_APP_ENDPOINT_V3')}\""
            buildConfigField "String", "PARAGON_ENDPOINT", "\"${configProps.getProperty('PROD_PARAGON_ENDPOINT')}\""
            buildConfigField "String", "PARAGON_HEADER", "\"${configProps.getProperty('PROD_PARAGON_HEADER')}\""
            buildConfigField "String", "NHS_LOGIN_URL", "\"${configProps.getProperty('PROD_NHS_LOGIN_URL')}\""
            buildConfigField "String", "NHS_SETTINGS_URL", "\"${configProps.getProperty('PROD_NHS_SETTINGS_URL')}\""
            buildConfigField "String", "OIDC_DISCOVERY_URL", "\"${configProps.getProperty('PROD_OIDC_DISCOVERY_URL')}\""
            buildConfigField "String", "PARAGON_TOKEN", "\"${configProps.getProperty('PROD_PARAGON_TOKEN')}\""
            resValue "string", "app_name", "Active 10"
            applicationId "uk.ac.shef.oak.pheactiveten"
        }
    }

    compileOptions {
        coreLibraryDesugaringEnabled true

        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    buildFeatures {
        viewBinding true
        dataBinding true
        compose true
    }

    composeOptions {
        kotlinCompilerExtensionVersion = "1.5.10"
    }
}

dependencies {
    implementation 'androidx.compose.foundation:foundation-android:1.6.8'
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.0.3'

    implementation project(path: ':BriskCounter')
    implementation "com.phe.betterhealth:ui-components:1.4.0-SNAPSHOT"

    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-rx2:1.7.3'

    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.core:core-splashscreen:1.0.1'
    implementation 'androidx.activity:activity-ktx:1.7.2'
    implementation "androidx.appcompat:appcompat:1.6.1"
    implementation "androidx.fragment:fragment-ktx:1.6.1"
    implementation 'androidx.annotation:annotation:1.7.0'

    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.6.2'
    implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.6.2'
    implementation 'androidx.lifecycle:lifecycle-common-java8:2.6.2'

    implementation "androidx.constraintlayout:constraintlayout:2.1.4"
    implementation "androidx.recyclerview:recyclerview:1.3.1"
    implementation "androidx.appcompat:appcompat:1.6.1"
    implementation "com.google.android.material:material:1.9.0"
    implementation 'androidx.viewpager2:viewpager2:1.0.0'
    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0"

    implementation "androidx.work:work-runtime-ktx:2.8.1"
    implementation "androidx.work:work-rxjava2:2.8.1"
    implementation "androidx.concurrent:concurrent-futures:1.1.0"

    implementation "com.afollestad.material-dialogs:core:3.3.0"
    implementation 'com.makeramen:roundedimageview:2.3.0'
    implementation 'com.airbnb.android:lottie:6.1.0'
    implementation 'com.github.PhilJay:MPAndroidChart:v3.1.0'
    implementation 'com.github.prolificinteractive:material-calendarview:2.0.0'
    implementation 'com.github.skydoves:balloon:1.5.4'

    implementation "com.google.android.gms:play-services-fitness:21.1.0"
    implementation 'com.google.android.gms:play-services-auth:20.7.0'

    implementation "com.google.android.play:review:2.0.1"
    implementation "com.google.android.play:review-ktx:2.0.1"

    implementation platform('com.google.firebase:firebase-bom:33.7.0')
    implementation 'com.google.firebase:firebase-crashlytics-ktx'
    implementation "com.google.firebase:firebase-messaging-ktx"
    implementation "com.google.firebase:firebase-analytics-ktx"
    implementation "com.google.firebase:firebase-perf-ktx"

    implementation 'com.google.code.gson:gson:2.10.1'
    implementation "net.danlew:android.joda:2.12.5"
    implementation 'org.jsoup:jsoup:1.16.1'
    implementation 'com.airbnb.android:paris:2.0.2'
    ksp 'com.airbnb.android:paris-processor:2.0.2'
    implementation 'com.github.bumptech.glide:glide:4.16.0'
    ksp 'com.github.bumptech.glide:compiler:4.16.0'
    implementation 'io.coil-kt:coil:2.4.0'
    implementation 'com.jakewharton.timber:timber:5.0.1'
    implementation "com.github.YarikSOffice:lingver:1.3.0"
    implementation 'com.pierfrancescosoffritti.androidyoutubeplayer:core:12.1.0'
    implementation 'com.github.tapadoo:alerter:7.2.4'
    implementation 'com.guolindev.permissionx:permissionx:1.7.1'

    implementation "com.squareup.retrofit2:retrofit:2.9.0"
    implementation "com.squareup.retrofit2:converter-gson:2.9.0"
    implementation "com.squareup.retrofit2:adapter-rxjava2:2.9.0"
    implementation "com.squareup.okhttp3:logging-interceptor:4.11.0"
    implementation 'net.openid:appauth:0.11.1'

    implementation 'io.reactivex.rxjava2:rxjava:2.2.21'
    implementation 'io.reactivex.rxjava2:rxandroid:2.1.1'
    implementation 'com.jakewharton.rxbinding2:rxbinding-kotlin:2.2.0'
    implementation "io.reactivex.rxjava2:rxkotlin:2.4.0"

    implementation 'com.google.dagger:dagger:2.48'
    implementation 'com.google.dagger:dagger-android-support:2.48'

    // Jetpack Compose
    implementation(platform("androidx.compose:compose-bom:2024.02.02"))
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.ui:ui-tooling-preview")
    implementation("androidx.compose.material3:material3")
    implementation "io.coil-kt:coil-compose:2.1.0"

    kapt 'com.google.dagger:dagger-android-processor:2.48'
    kapt 'com.google.dagger:dagger-compiler:2.48'

    // Root check
    implementation 'com.scottyab:rootbeer-lib:0.1.0'
    // Play Integrity API
    implementation 'com.google.android.play:integrity:1.4.0'

    // PageIndicator for Tooltips
    implementation 'com.github.adrielcafe:PageIndicatorView:1.0.6'

    // Biometric
    implementation "androidx.biometric:biometric-ktx:1.4.0-alpha02"

    // JWT library
    api('io.jsonwebtoken:jjwt-api:0.12.6')
    runtimeOnly('io.jsonwebtoken:jjwt-impl:0.12.6')
    runtimeOnly('io.jsonwebtoken:jjwt-orgjson:0.12.6') {
        exclude(group: 'org.json', module: 'json') //provided by Android natively
    }

//    Bitrise has a problem with this dependency
//    debugImplementation 'com.github.amitshekhariitbhu.Android-Debug-Database:debug-db:1.0.6'

    testImplementation 'junit:junit:4.13.2'
    testImplementation "io.mockk:mockk:1.13.5"
}


licensee {
    allow('Apache-2.0')
    allow('MIT')
    allow('BSD-3-Clause')
    allow('CC0-1.0')
    allowUrl("https://developer.android.com/studio/terms.html") {
        because 'Android Studio Terms of Service'
    }
    allowUrl("https://developer.android.com/guide/playcore/license") {
        because 'Play Core Library License'
    }
    allowUrl("https://opensource.org/licenses/MIT") {
        because 'MIT License'
    }
    allowUrl("https://github.com/PierfrancescoSoffritti/android-youtube-player/blob/master/LICENSE") {
        because 'MIT License'
    }
    allowUrl("https://jsoup.org/license") {
        because 'MIT License'
    }
    allowUrl("https://developer.android.com/google/play/integrity/overview#tos") {
        because 'Google Play Integrity Terms of Service'
    }
    allowUrl("https://raw.githubusercontent.com/ThreeTen/threetenbp/master/LICENSE.txt") {
        because 'BSD-3-Clause License'
    }
    allowUrl("https://github.com/afollestad/material-dialogs/blob/main/LICENSE.md") {
        because 'Apache-2.0 License'
    }
    allowDependency("com.airbnb.android", "paris", "2.0.2") {
        because 'Apache-2.0 License'
    }
    allowDependency("com.airbnb.android", "paris-annotations", "2.0.2") {
        because 'Apache-2.0 License'
    }
    allowDependency("com.github.PhilJay", "MPAndroidChart", "v3.1.0") {
        because 'Apache-2.0 License'
    }
    allowDependency("com.github.YarikSOffice", "lingver", "1.3.0") {
        because 'MIT License'
    }
    allowDependency("com.github.prolificinteractive", "material-calendarview", "2.0.0") {
        because 'MIT License'
    }
    allowDependency("com.github.amitshekhariitbhu.Android-Debug-Database", "debug-db", "1.0.6") {
        because 'Apache-2.0 License'
    }
    allowDependency("com.github.amitshekhariitbhu.Android-Debug-Database", "debug-db-base", "1.0.6") {
        because 'Apache-2.0 License'
    }
    allowDependency("com.phe.betterhealth", "ui-components", "1.4.0-SNAPSHOT") {
        because 'TODO ' // TODO: set license
    }
}
