DEV_APP_ENDPOINT=https://example.invalid/
DEV_APP_ENDPOINT_V3=https://example.invalid/
DEV_PARAGON_ENDPOINT=https://example.invalid/
DEV_NHS_LOGIN_URL=https://example.invalid/
DEV_NHS_SETTINGS_URL=https://example.invalid/
DEV_PARAGON_HEADER=dummy
DEV_PARAGON_TOKEN=dummy

UAT_APP_ENDPOINT=https://example.invalid/
UAT_APP_ENDPOINT_V3=https://example.invalid/
UAT_PARAGON_ENDPOINT=https://example.invalid/
UAT_NHS_LOGIN_URL=https://example.invalid/
UAT_NHS_SETTINGS_URL=https://example.invalid/
UAT_PARAGON_HEADER=dummy
UAT_PARAGON_TOKEN=dummy

PROD_APP_ENDPOINT=https://example.invalid/
PROD_APP_ENDPOINT_V3=https://example.invalid/
PROD_PARAGON_ENDPOINT=https://example.invalid/
PROD_NHS_LOGIN_URL=https://example.invalid/
PROD_NHS_SETTINGS_URL=https://example.invalid/
PROD_PARAGON_HEADER=dummy
PROD_PARAGON_TOKEN=dummy

CERTIFICATE_1=dummy
CERTIFICATE_2=dummy
CERTIFICATE_3=dummy
CERTIFICATE_4=dummy
CERTIFICATE_5=dummy

GOOGLE_MAPS_API_KEY=dummy
